- name: Update APT cache
  apt:
    update_cache: yes
    cache_valid_time: "{{ cache_valid_time }}"

- name: Install Midnight Commander
  apt:
    name: mc
    state: present

- name: "=> Install Node Exporter for monitoring"
  import_tasks: node-exporter.yml
