- name: Add an APT signing key for Grafana
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana repository into sources list
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: Update repositories cache and install Grafana package
  apt:
    name: grafana
    update_cache: yes

- name: Enable Grafana service and ensure it is not masked
  systemd:
    state: started
    name: grafana-server
    enabled: yes
    masked: no