- name: Install NGINX package
  apt:
    name: nginx
    state: present

- name: Disable default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Add site config
  template:
    src: nginx/default.conf
    dest: /etc/nginx/sites-available/site.conf

- name: Enable site
  file:
    src: /etc/nginx/sites-available/site.conf
    dest: /etc/nginx/sites-enabled/site.conf
    state: link

- name: Restart NGINX service
  service:
    name: nginx
    state: restarted